import SWRFetchTester from "@/components/SWRFetchTester";
import Head from "next/head";
import Footer from "@/components/footer/Footer";

export default function Home() {
	return (
		<>
			<Head>
				<title>Home Chow</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<SWRFetchTester />
				<h1>Footer</h1>
				<Footer />
			</div>
		</>
	);
}
