import SWRFetchTester from "@/components/SWRFetchTester";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export async function getStaticProps({ locale }: { locale: string }) {
	return {
		props: {
			...(await serverSideTranslations(locale ?? "en", ["comman", "footer"])),
		},
	};
}

export default function Home() {
	return (
		<>
			<Head>
				<title>Home Chow</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<SWRFetchTester />
			</div>
		</>
	);
}
