name: ci

on: [push, pull_request]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies"
          bun install

      - name: Run Lint
        run: |
          echo "Running Lint"
          bun run lint
        env:
          CI: true
