name: Cypress Tests

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: E2E Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build App
        run: yarn build
      - name: Start App
        run: yarn start &
      - name: Wait for App to Start
        run: |
          n=0
          until [ $n -ge 15 ]
          do
            curl -I http://localhost:3003 && break
            n=$((n+1))
            sleep 1
          done
      - name: Run E2E Tests
        run: yarn cypress:run
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: ./cypress/videos

  component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Run Component Tests
        run: yarn run cypress:comp

  artifact:
    needs: [e2e]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
